services:
  db:
    image: mysql
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: Saedhappy@2020
      MYSQL_DATABASE: authentication
    ports:
      - "6033:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
    driver: local